version: "3"
services:
  frontend:
    image: ghcr.io/suptar21/projectii-frontend:master
    container_name: studart-frontend
    ports:
      - "8080:80"

networks:
  default:
    external:
      name: studart-database-network
